version: "3.9"
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 3300:3300
    environment:
      - PORT=3300
      - LND_MACAROON=${LND_MACAROON}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - LND_ENDPOINT=${LND_ENDPOINT}
    networks:
      backend:

  pwa:
    build:
      context: ./next-app
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3300/api
    ports:
      - 4000:4000
    networks:
      backend:

  dwn-server:
    image: ghcr.io/tbd54566975/dwn-server:main
    container_name: dwn-server
    ports:
      - 3000:3000
    volumes:
      - ./dwn-data:/dwn-server/data
    networks:
      - backend

networks:
  backend:
